name: CD

on:
  push:
   tags:
     - '*'

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        components: clippy

    - name: Setup MUSL
      if: matrix.os == 'ubuntu-latest'
      run: |
        rustup target add x86_64-unknown-linux-musl
        sudo apt-get -qq install musl-tools

    - name: Setup Linux i686
      if: matrix.os == 'ubuntu-latest'
      run: |
        rustup target add i686-unknown-linux-gnu
        sudo apt-get -qq install gcc-multilib

    - name: Build Release Mac
      if: matrix.os == 'macos-latest'
      run: make release-mac

    - name: Build Release Linux Musl
      if: matrix.os == 'ubuntu-latest'
      run: make release-linux-musl release-linux

    - name: Build Release Linux
      if: matrix.os == 'ubuntu-latest'
      run: make release-linux

    - name: Build Release Win
      if: matrix.os == 'windows-latest'
      run: make release-win

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: false
        files: |
          ./release/*.tar.gz
          ./release/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
