name: CD

on:
  push:
   tags:
     - '*'

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Get version
      id: get_version
      run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        components: clippy

    - name: Build
      run: cargo build
    - name: Run tests
      run: make test

    - name: Setup MUSL
      if: matrix.os == 'ubuntu-latest'
      run: |
        rustup target add x86_64-unknown-linux-musl
        sudo apt-get -qq install musl-tools

    - name: Setup Linux i686
      if: matrix.os == 'ubuntu-latest'
      run: |
        rustup target add i686-unknown-linux-gnu

    - name: Build Release Mac
      if: matrix.os == 'macos-latest'
      run: make release-mac

    - name: Build Release Linux
      if: matrix.os == 'ubuntu-latest'
      run: make release-linux-musl release-linux

    - name: Build Release Win
      if: matrix.os == 'windows-latest'
      run: make release-win

    - name: Set SHA
      if: matrix.os == 'macos-latest'
      id: shasum
      run: |
        echo ::set-output name=sha::"$(shasum -a 256 ./release/gitui-mac.tar.gz | awk '{printf $1}')"

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: false
        files: |
          ./release/*.tar.gz
          ./release/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
