name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        components: clippy

    - name: Build Debug
      run: |
        rustc --version
        cargo build

    - name: Run tests
      run: make test

    - name: Run clippy
      run: |
        make clippy

  build-linux-musl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        target: x86_64-unknown-linux-musl

    - name: Setup MUSL
      run: |
        sudo apt-get -qq install musl-tools
    - name: Build Debug
      run: cargo build --target=x86_64-unknown-linux-musl

  #rustfmt:
    #name: Rustfmt
    #runs-on: ubuntu-latest
    #steps:
    #- uses: actions/checkout@master
    #- name: Install Rust
      #uses: actions-rs/toolchain@v1
      #with:
        #toolchain: stable
        #components: rustfmt
    #- run: cargo fmt -- --check
